# Generated by Django 6.1.1 on 2026-09-10 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получено"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Должность / специальность"
                    ),
                ),
                (
                    "organization",
                    models.CharField(max_length=100, verbose_name="Организация"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "kind",
                    models.CharField(
                        choices=[("work", "Работа"), ("education", "Образование")],
                        default="work",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт",
                "verbose_name_plural": "Опыт и образование",
                "ordering": ["order", "-start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Имя и фамилия"),
                ),
                ("role", models.CharField(max_length=150, verbose_name="Должность")),
                ("bio", models.TextField(verbose_name="О себе")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="profile/", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Локация"
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, upload_to="cv/", verbose_name="Файл резюме"
                    ),
                ),
                (
                    "cv_url",
                    models.URLField(blank=True, verbose_name="Ссылка на резюме"),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(default=0, verbose_name="Лет опыта"),
                ),
                (
                    "projects_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество проектов"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Открыт к предложениям"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профиль",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Уровень, %",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Иконка (эмодзи)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория навыков",
                "verbose_name_plural": "Категории навыков",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соцсеть",
                "verbose_name_plural": "Соцсети",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Слаг (URL)"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Краткое описание"
                    ),
                ),
                ("description", models.TextField(verbose_name="Полное описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="projects/", verbose_name="Обложка"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("web", "Веб-приложение"),
                            ("mobile", "Мобильное приложение"),
                            ("api", "API-сервис"),
                            ("bot", "Бот"),
                        ],
                        db_index=True,
                        default="web",
                        max_length=10,
                        verbose_name="Тип проекта",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, verbose_name="Ссылка на GitHub"),
                ),
                (
                    "live_url",
                    models.URLField(blank=True, verbose_name="Ссылка на демо"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Показать в избранном"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="main.skill", verbose_name="Технологии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="main.skillcategory",
                verbose_name="Категория",
            ),
        ),
    ]
